### ISSUE TITLE
Slice assignment causes an adverbed zen slice to omit the final element

### ISSUE THREAD

**Issue by raydiak** [lizmat/Array-Sparse#3]
```
my @a is Array::Sparse;
@a[0,1] = <a b>;
say @a[]:v;
# OUTPUT: «(a)␤»
```

Changing/removing any of these factors hides the bug:
- is Array::Sparse
    - not a core Array
- list assignment to a non-zen slice
    - not list assignment to the whole array
    - not a zen slice
    - not procedural assignment to individual indices
- zen slice retrieval
    - indexing with Whatever in the forms `[*]` and `[^*]` also trigger the bug, but `[0..*]` and `[0..^*]` do not
    - not the whole array itself
    - not a slice of ranges/values whether explicitly bounded or infinite
- must be adverbed
    - all adverbs tested do show this same behavior, including :k, :v, :kv, and :p
    - not the equivalent method calls

**Comment by raydiak** [comment]
Apologies for the edit churn. I was briefly chasing my tail in circles while double-checking my assertions and attempting to better define the behavior

**Comment by lizmat** [comment]
No worries, thanks for the investigative work.  Will look at it after the RWN.
